version: '3.8'
services:
  auction-service:
    build:
      context: ./auction-service
      dockerfile: Dockerfile
    volumes:
      - ./auction-service:/var/www
    depends_on:
      - mysql
      - redis
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - DB_HOST=mysql
      - DB_DATABASE=auctions
      - DB_USERNAME=root
      - DB_PASSWORD=secret
      - REDIS_HOST=redis

  nginx:
    image: nginx:latest
    ports:
      - "8000:80"
    volumes:
      - ./auction-service:/var/www
      - ./auction-service/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - auction-service

  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=auctions
    volumes:
      - mysql-data:/var/lib/mysql

  redis:
    image: redis:latest
    volumes:
      - redis-data:/data

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - "8080:80"
    environment:
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=secret
    depends_on:
      - mysql

volumes:
  mysql-data:
  redis-data: